# Generated by Django 5.2.7 on 2025-11-15 23:11

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=32, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_path', models.CharField(blank=True, max_length=128, unique=True, verbose_name='caminho completo')),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'seção',
                'verbose_name_plural': 'seções',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='descrição')),
                ('cover', models.URLField(blank=True, verbose_name='capa')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('published_at', models.DateTimeField(editable=False, null=True, verbose_name='publicado em')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=16)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='posts.category', verbose_name='categorias')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.section', verbose_name='seção')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
