# Generated by Django 5.2.7 on 2025-12-02 02:44

import django.db.models.deletion
import posts.utils.upload_to
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='descrição')),
                ('cover', models.ImageField(blank=True, upload_to=posts.utils.upload_to.post_image_path, verbose_name='capa')),
                ('video', models.URLField(blank=True, verbose_name='vídeo')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('published_at', models.DateTimeField(editable=False, null=True, verbose_name='publicado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=32, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('full_path', models.CharField(blank=True, max_length=128, unique=True, verbose_name='caminho completo')),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('is_review', models.BooleanField(default=False, verbose_name='é review')),
                ('is_opinion', models.BooleanField(default=False, verbose_name='é opinião')),
            ],
            options={
                'verbose_name': 'artigo',
            },
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='é urgente')),
            ],
            options={
                'verbose_name': 'notícia',
            },
            bases=('posts.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.category', verbose_name='categorias'),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('prerequisites', models.ManyToManyField(blank=True, to='posts.tutorial', verbose_name='pré-requisitos')),
            ],
            options={
                'verbose_name_plural': 'tutoriais',
            },
            bases=('posts.post',),
        ),
    ]
