# Generated by Django 5.2.7 on 2025-12-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_description_tutorial_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='prerequisites',
        ),
    ]
