# Generated by Django 5.2.7 on 2025-12-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_article_is_opinion_remove_article_is_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
