# Generated by Django 5.2.7 on 2025-12-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
    ]
