# Generated by Django 5.2.7 on 2025-11-15 23:11

import django.db.models.deletion
import uploads.utils.upload_to
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ImageField(max_length=128, upload_to=uploads.utils.upload_to.post_image_source_path, verbose_name='fonte')),
                ('processed', models.ImageField(blank=True, max_length=128, upload_to=uploads.utils.upload_to.post_image_processed_path, verbose_name='processada')),
                ('kind', models.CharField(choices=[('post_cover', 'Capa do Post'), ('post_content_image', 'Imagem do Conteúdo do Post')], max_length=20, verbose_name='tipo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='posts.post')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.FileField(max_length=128, upload_to=uploads.utils.upload_to.post_video_source_path, verbose_name='fonte')),
                ('processed', models.FileField(blank=True, max_length=128, upload_to=uploads.utils.upload_to.post_video_processed_path, verbose_name='processado')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to='posts.post')),
            ],
            options={
                'verbose_name': 'vídeo',
            },
        ),
    ]
