# Generated by Django 5.2.7 on 2025-11-07 04:12

import django.db.models.deletion
import uploads.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(verbose_name='processado')),
                ('image', models.ImageField(upload_to=uploads.models.upload_post_image_to_path, verbose_name='imagem')),
                ('kind', models.CharField(choices=[('post_cover', 'Capa do Post'), ('post_content_image', 'Imagem do Conteúdo do Post')], max_length=20, verbose_name='tipo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='posts.post')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(verbose_name='processado')),
                ('video', models.FileField(upload_to=uploads.models.upload_post_video_to_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to='posts.post')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'Vídeo',
            },
        ),
    ]
