# Generated by Django 5.2.7 on 2025-12-12 14:23

import products.utils.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.FileField(default='https://www.svgrepo.com/show/535588/question-mark.svg', upload_to=products.utils.upload_to.platform_logo_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
